Freundschaftsanfragen
DenKedi/se-backend pull request #4
Opened 2024-12-17 22:38 UTC by DenKedi

Checkt 5 Cases bei versenden einer Freundschaftsanfrage: 

1. Der Sender kann sich nicht selbst eine Freundschaftsanfrage senden.
Überprüft, ob der Sender und Empfänger dieselbe Person sind.

2. Der Sender hat eine ausstehende Anfrage vom Empfänger.
Überprüft, ob der Sender bereits eine ausstehende Anfrage vom Empfänger hat und akzeptiert diese, falls vorhanden.

3. Der Sender und Empfänger sind bereits Freunde.
Überprüft, ob der Sender und Empfänger bereits in der Freundesliste sind.

4. Der Sender hat bereits eine abgelehnte oder ausstehende Anfrage an den Empfänger gesendet.
Überprüft, ob eine bestehende Anfrage vom Sender an den Empfänger vorhanden ist und ob diese abgelehnt oder noch ausstehend ist.

5. Der Sender hat noch keine Anfrage an den Empfänger gesendet.
Wenn keine der vorherigen Bedingungen zutrifft, wird eine neue Freundschaftsanfrage an den Empfänger gesendet.

2024-12-21 16:54 UTC, mirih2o approved these changes

2024-12-22 15:13 UTC, tommyngo98 requested changes

2024-12-22 15:13 UTC, tommyngo98 commented on package.json
> +    "se-backend": "file:",
Was macht diese line?

2024-12-22 15:13 UTC, tommyngo98 commented on routes/userRoutes.js
> +  if (!Receiver) {
``
```suggestion
  if (!receiver) {
```

2024-12-22 15:13 UTC, tommyngo98 commented on routes/userRoutes.js
> +    return res.status(404).json({ msg: "User nicht gefunden" });
```suggestion
    return res.status(404).json({ msg: "Benutzer nicht gefunden" });
```

Würds am besten einheitlich halten, also entweder immer "User" oder immer "Benutzer". Oder User wenn englisch genutzt wird und benutzer wenn deutsch

2024-12-22 15:13 UTC, tommyngo98 commented on utils/userService.js
> +
```suggestion
```

2024-12-22 15:13 UTC, tommyngo98 commented on utils/userService.js
> +
```suggestion
```

2024-12-22 15:13 UTC, tommyngo98 commented on utils/userService.js
> +    if (receiver._id.toString() === sender._id.toString()) {
die cases die keinen error werfen, müssen nicht in den try-block oder?

2024-12-22 15:13 UTC, tommyngo98 commented on utils/userService.js
> +
```suggestion
```

2024-12-22 15:13 UTC, tommyngo98 commented on routes/userRoutes.js
> +
```suggestion
```

2024-12-22 15:13 UTC, tommyngo98 commented on utils/userService.js
> +async function acceptAsFriends(sender, receiver) {
```suggestion
async function acceptFriendRequest(sender, receiver) {
```

maybe umbennen damit es ins schema passt (handle, deny, accept)

2024-12-22 15:13 UTC, tommyngo98 commented on utils/userService.js
> +    return user; // Return the user
```suggestion
    return user;
```
Kommentar kann weg

2024-12-22 15:19 UTC, DenKedi commented on package.json
> +    "se-backend": "file:",
kein plan actually

2024-12-22 15:20 UTC, DenKedi commented on routes/userRoutes.js
> +  if (!Receiver) {
yes

2024-12-22 15:20 UTC, DenKedi commented on routes/userRoutes.js
> +    return res.status(404).json({ msg: "User nicht gefunden" });
kk

2024-12-23 12:41 UTC, merged